"use client";

import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { UserDetailsContext } from "./(routes)/_context/UserDetailsContext";
import { useState } from "react";

const outfit = Outfit({ subsets: ["latin"] });

/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {

  const [userDetails, setUserDetails] = useState();
  return (
    <ClerkProvider>
      <UserDetailsContext.Provider value={{userDetails, setUserDetails}}>
        <html lang="en">
          <body className={outfit.className}>{children}</body>
        </html>
      </UserDetailsContext.Provider>
    </ClerkProvider>
  );
}
